### ISSUE TITLE
Ошибка при инициализации Az.Morph.init

### ISSUE THREAD

**Issue by vladshov** [deNULL/Az.js#1]
Добрый день! Не могли бы вы подсказать в чем может быть причина следующей ошибки при выполнении кода 

Az.Morph.init('node_modules/az/dicts', function() {
  var parses = Az.Morph('стали');
  console.log(parses); // => 6 вариантов разбора
  console.log(parses[0].tag.toString()); // => 'VERB,perf,intr plur,past,indc'
  console.log(parses[1].tag.toString()); // => 'NOUN,inan,femn plur,nomn'
});
  
Ошибка:
 var dv = new DataView(data),
             ^
Error: Object must be an ArrayBuffer.
    at Function.DAWG.fromArrayBuffer (node_modules\az\dist\az.js:127:14)
    at node_modules\az\dist\az.js:138:39
    at node_modules\az\dist\az.js:24:13
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)

**Comment by deNULL** [comment]
Судя по всему, не удалось загрузить один из файлов словаря (words.dawg, prediction-suffixes-*.dawg, p_t_given_w.intdawg). Они действительно должны быть в 'node_modules/az/dicts' (хотя при использовании npm этот параметр можно опустить), но ошибка говорит о том, что почему-то прочитать их не удалось.

У меня такое поведение не воспроизводится.

Судя по слэшам, у вас Windows. Какая версия node?

**Comment by vladshov** [comment]
Да, Windows. Версия node 0.10.26

**Comment by vovadihtyar** [comment]
Ты наверно ошибся мылом.

2016-06-16 14:54 GMT+03:00 vladshov <notifications@github.com>:

**Comment by deNULL** [comment]
Теперь должно загружать словари и на старой ноде. Не очень быстро, но работать должно.
