### ISSUE TITLE
Пытаюсь юзать либку, в консоле выдаёт fs.readFile is not a function

### ISSUE THREAD

**Issue by VladislavMarkevich** [deNULL/Az.js#10]
Пытаюсь запустить
Az.Morph.init('node-modules/az/dicts', function() {
        var parses = Az.Morph('стали');
        console.log(parses); // => 6 вариантов разбора
        console.log(parses[0].tag.toString()); // => 'VERB,perf,intr plur,past,indc'
        console.log(parses[1].tag.toString()); // => 'NOUN,inan,femn plur,nomn'
      });

Чекал код библиотеки, по идее должен был работать для винди и без первого параметра, но почему-то у меня не работает))

бьёт в файле az.js
строчка 14
        fs.readFile(url, { encoding: responseType == 'json' ? 'utf8' : null }, function (err, data) {

Может я чего не понимаю, подскажи как пофиксить ПЖ или расскажи чё нужно для работы

**Comment by KotskinKotskin** [comment]
@VladislavMarkevich  как пофиксил?

**Comment by ivashov-clearscale** [comment]
@VladislavMarkevich Владислав, нашлось ли решение этой проблемы? Поделитесь решением пожалуйста

**Comment by lih1989** [comment]
Была такая проблема, решилась изменением пути к словарям:
'node-modules/az/dicts' --> '../node-modules/az/dicts'
